# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210221_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Laboratory'),
        ),
    ]
