# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'db_table': 'newsletter_subscription',
                'abstract': False,
            },
        ),
    ]
