# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-21 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0049_auto_20201117_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='funders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_funders', to=settings.AUTH_USER_MODEL),
        ),
    ]
