# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0054_auto_20210224_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='default_funding_target',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
