# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0055_submissionconfiguration_default_funding_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'date_published', 'ordering': ('-date_published', 'title')},
        ),
    ]
