# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210203_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='enable_public_profile',
            field=models.BooleanField(default=True, help_text='If enabled, your basic profile will be available to the public.'),
        ),
    ]
