# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210221_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enable_sponsor',
            field=models.BooleanField(default=False, help_text='If enabled, activate sponsoring mode.'),
        ),
    ]
