# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-25 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0002_auto_20170816_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(verbose_name='Write your comment:')),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_news_item', to='comms.NewsItem')),
            ],
            options={
                'ordering': ('-date_time', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='comms.Comment'),
        ),
    ]
