# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_auto_20210505_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='large_image_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='large_news_file', to='core.File'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
