# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0052_auto_20210224_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='target_funding',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='funding_target',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
