# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0053_auto_20210224_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionconfiguration',
            old_name='target_funding',
            new_name='funding_target',
        ),
    ]
