# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0056_auto_20210407_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'date_updated', 'ordering': ('-date_published', 'title')},
        ),
    ]
