# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprint', '0012_comment_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprint',
            options={'get_latest_by': 'current_version'},
        ),
        migrations.RenameField(
            model_name='preprint',
            old_name='curent_version',
            new_name='current_version',
        ),
    ]
